name: rust-keylock-ui
version: '0.10.0'
summary: A password manager written (mostly) in Rust
description: |
  rust-keylock is a password manager and its goals are to be:
     - Secure
     - Simple to use
     - Portable
     - Extensible
  The core logic is written in Rust, but the presentation/User interaction parts are in different languages.
  rust-keylock-ui manages the rust-keylock core, providing a User Interface using JavaFX (via ScalaFX).

grade: stable
confinement: strict
icon: snap/gui/rkl.png
base: core18

parts:
  rust-keylock-ui-all:
    plugin: maven
    source: https://github.com/rust-keylock/rust-keylock-ui.git
    #    source-tag: v0.10.0
    override-build: |
      export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-${SNAP_ARCH}"
      # Setup Rust
      BASEDIR=`pwd`
      mkdir -p $BASEDIR/tools/.cargo
      mkdir -p $BASEDIR/tools/.rustup
      export CARGO_HOME=$BASEDIR/tools/.cargo
      RUSTUP_HOME=$BASEDIR/tools/.rustup
      PATH=$CARGO_HOME/bin:$PATH
      curl https://sh.rustup.rs -sSf > $BASEDIR/tools/rustup.sh
      chmod +x $BASEDIR/tools/rustup.sh
      CARGO_HOME=$BASEDIR/tools/.cargo RUSTUP_HOME=$BASEDIR/tools/.rustup sh tools/rustup.sh --no-modify-path -y
      $CARGO_HOME/bin/rustup default stable
      # Build rust-keylock-ui-rust
      echo Building rust-keylock-ui-rust
      export RKL_J4RS_INST_DIR=$BASEDIR/j4rs
      mkdir -p $RKL_J4RS_INST_DIR
      cd $BASEDIR
      $CARGO_HOME/bin/cargo build --manifest-path=rust/Cargo.toml --release
    build-packages:
      - openjdk-11-jdk
      - openssl
      - libssl-dev
      - git
      - libxcb-shape0
      - libxcb-shape0-dev
      - libxcb-xfixes0
      - libxcb-xfixes0-dev
    stage-packages:
      - openjdk-11-jdk
      - openssl
      - libssl1.0.0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb-render0
    organize:
      ../build/j4rs: opt/j4rs
      ../build/rust/target/release/rust-keylock-ui: bin/
  desktop-glib-only:
    build-packages:
      - libglib2.0-dev
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    stage-packages:
      - libglib2.0-bin
  env:
    plugin: nil
    after:
      - rust-keylock-ui-all
      - desktop-glib-only
apps:
  rust-keylock-ui:
    command: desktop-launch $SNAP/bin/rust-keylock-ui
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - opengl
      - network
      - wayland
    environment:
      RKL_J4RS_INST_DIR: ${SNAP}/opt/j4rs
      JAVA_HOME: ${SNAP}/usr/lib/jvm/java-11-openjdk-${SNAP_ARCH}
      RUST_KEYLOCK_UI_JAVA_USER_HOME: ${HOME}